services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis/data:/data
    networks:
      - live-data-nw
    ports:
      - 127.0.0.1:6379:6379
  live-data-1:
    container_name: live-data-1
    build: ./server
    command: npm start
    volumes: 
      - ./server:/app
    ports: 
      - 3000:3000
    depends_on:
      - redis
    environment:
      - PORT=3000
    networks:
      - live-data-nw
  live-data-2:
    container_name: live-data-2
    build: ./server
    command: npm start
    volumes: 
      - ./server:/app
    ports: 
      - 3001:3001
    depends_on:
      - redis
    environment:
      - PORT=3001
    networks:
      - live-data-nw
  live-data-client-1:
    container_name: live-data-client-1
    build: ./client
    command: npm start
    volumes: 
      - ./client:/app
    ports: 
      - 8080:8080
    depends_on:
      - live-data-1
      - live-data-2
    environment:
      - PORT=8080
    networks:
      - live-data-nw
  live-data-client-2:
    container_name: live-data-client-2
    build: ./client
    command: npm start
    volumes: 
      - ./client:/app
    ports: 
      - 8081:8081
    depends_on:
      - live-data-1
      - live-data-2
    environment:
      - PORT=8081
    networks:
      - live-data-nw
networks:
  live-data-nw:
    external: true
